[2024-04-20T16:11:28.624+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T16:11:26.692963+00:00 [queued]>
[2024-04-20T16:11:28.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T16:11:26.692963+00:00 [queued]>
[2024-04-20T16:11:28.635+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-20T16:11:28.650+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-04-20 16:11:26.692963+00:00
[2024-04-20T16:11:28.661+0000] {standard_task_runner.py:57} INFO - Started process 64 to run task
[2024-04-20T16:11:28.663+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-04-20T16:11:26.692963+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpwnaeyuyv']
[2024-04-20T16:11:28.666+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask reddit_extraction
[2024-04-20T16:11:28.717+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T16:11:26.692963+00:00 [running]> on host a5ce8015e481
[2024-04-20T16:11:28.818+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tawfik Yasser' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T16:11:26.692963+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T16:11:26.692963+00:00'
[2024-04-20T16:11:29.442+0000] {logging_mixin.py:151} INFO - Number of posts = 10
[2024-04-20T16:11:29.442+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 26, in reddit_pipeline
    transformed_data = transform_posts(posts_df)
  File "/opt/airflow/etls/reddit_etl.py", line 13, in transform_posts
    post_df['created'] = pd.to_datetime(post_df['created'], unit='s')
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3896, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/range.py", line 418, in get_loc
    raise KeyError(key)
KeyError: 'created'
[2024-04-20T16:11:29.461+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240420T161126, start_date=20240420T161128, end_date=20240420T161129
[2024-04-20T16:11:29.471+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task reddit_extraction ('created'; 64)
[2024-04-20T16:11:29.519+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-20T16:11:29.537+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
